[versions]
agp = "8.2.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
# CAMBIO 1: Esta es una versión válida y moderna que sí existe en Maven Central
webrtc = "114.5735.07"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
# CAMBIO 2: Cambiamos 'org.webrtc' por 'io.github.webrtc-sdk' para que lo descargue del sitio correcto
webrtc = { group = "io.github.webrtc-sdk", name = "android", version.ref = "webrtc" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
